apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auto-unseal-config
  labels:
    app.kubernetes.io/name: vault-auto-unseal
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-auto-unseal-cluster
data:
  config.hcl: |
    listener "tcp" {
    tls_disable = 1
    }
    disable_mlock = true
    raw_storage_endpoint     = true
    storage "raft" {
       path = "/vault/raft-db/"
       node_id = "auto-unseal-node"
    }

  autounseal.hcl: |
    path "transit/encrypt/autounseal" {
    capabilities = [ "update" ]
    }
    path "transit/decrypt/autounseal" {
    capabilities = [ "update" ]
    }