apiVersion: v1
kind: Service
metadata:
  name: vault-auto-unseal
  labels:
    app.kubernetes.io/name: vault-auto-unseal
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-auto-unseal-cluster
spec:
  type: ClusterIP
  ports:
        - name: http
          port: 8200
          targetPort: 8200

        - name: https
          port: 8201
          targetPort: 8201

        - name: init
          protocol: "TCP"
          port: 8202
          targetPort: 8202
  selector:
    app.kubernetes.io/name: vault-auto-unseal
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-auto-unseal-cluster
