apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-cluster
data:
  config.hcl: |
    listener "tcp" {
    tls_disable = 1
    }
    storage "consul" {
      address = "consul:8500"
      path    = "vault/"
    }
    disable_mlock = true
