apiVersion: v1
kind: Service
metadata:
  namespace: vault-cluster
  name: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-cluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
        - name: http
          port: 8200
          targetPort: 8200

        - name: https
          port: 8201
          targetPort: 8201

        - name: init
          protocol: "TCP"
          port: 8202
          targetPort: 8202

        - name: consul-http
          port: 8500
          targetPort: 8500

        - name: consul-https
          port: 8501
          targetPort: 8501

        - name: consul-serflan-tcp
          port: 8301
          targetPort: 8301
          protocol: "TCP"

        - name: consul-serflan-udp
          port: 8301
          targetPort: 8301
          protocol: "UDP"

        - name: consul-serfwan-tcp
          port: 8302
          targetPort: 8302
          protocol: "TCP"

        - name: consul-serfwan-udp
          port: 8302
          targetPort: 8302
          protocol: "UDP"

        - name: consul-server
          port: 8300
          targetPort: 8300

        - name: consul-dns-tcp
          port: 8600
          targetPort: 8600
          protocol: "TCP"

        - name: consul-dns-udp
          port: 8600
          targetPort: 8600
          protocol: "UDP"
            
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: vault-cluster
